name: Run blogmaker

on:
  push:
    branches: [master]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run blogmaker
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'
      - name: Install dependencies
        run: pip install markdown2 pygments
      - name: Run the script
        run: python blogmaker.py
